
package io.github.bodzisz;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://service.bodzisz.github.io/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws PersonNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.DeletePersonResponse")
    public boolean deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws PersonNotFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<io.github.bodzisz.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPersons", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.GetAllPersons")
    @ResponseWrapper(localName = "getAllPersonsResponse", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.GetAllPersonsResponse")
    public List<Person> getAllPersons();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countPersons", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.CountPersons")
    @ResponseWrapper(localName = "countPersonsResponse", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.CountPersonsResponse")
    public int countPersons();

    /**
     * 
     * @param arg0
     * @return
     *     returns io.github.bodzisz.Person
     * @throws PersonNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.GetPersonResponse")
    public Person getPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws PersonNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns io.github.bodzisz.Person
     * @throws PersonExistException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://service.bodzisz.github.io/", className = "io.github.bodzisz.AddPersonResponse")
    public Person addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws PersonExistException_Exception
    ;

}
