
package io.github.bodzisz;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PersonExistException", targetNamespace = "http://service.bodzisz.github.io/")
public class PersonExistException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonExistException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PersonExistException_Exception(String message, PersonExistException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    public PersonExistException_Exception() {}

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public PersonExistException_Exception(String message, PersonExistException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: io.github.bodzisz.PersonExistException
     */
    public PersonExistException getFaultInfo() {
        return faultInfo;
    }

}
